runtime: python38
service: default

handlers:
  - url: /(.*\..+)$
    secure: always
    static_files: dist/\1
    upload: dist/(.*\..+)$
  
  - url: /.*
    secure: always
    static_files: dist/index.html
    upload: dist/index.html
