runtime: python38
service: default

handlers:
  - url: /(.*\.(gif|png|jpg|ico|js|css))$
    static_files: dist/\1
    upload: dist/.*\.(gif|png|jpg|ico|js|css)$
  
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
